export default function LandingPage() {
  return (
    <div className="space-y-16 py-12">
      <section className="text-center max-w-4xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-700">
        <div className="inline-flex items-center rounded-full px-3 py-1 text-sm font-medium text-primary bg-primary/10 ring-1 ring-inset ring-primary/20 mb-4 hover:bg-primary/20 transition-colors cursor-default">
          ✨ Next-Gen Credit Scoring
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-slate-900 leading-tight">
          AI-Powered <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary via-vivid-500 to-purple-600">Credit Decisions</span>
        </h1>
        <p className="text-xl text-slate-600 leading-relaxed max-w-2xl mx-auto">
          Leverage alternative data signals like e-commerce behavior and digital wallet usage to assess creditworthiness with <span className="font-semibold text-slate-800">unmatched precision</span>.
        </p>
        <div className="flex flex-col sm:flex-row justify-center gap-4 pt-6">
          <a href="/score" className="px-8 py-4 rounded-xl bg-primary text-white font-bold text-lg hover:bg-opacity-90 transition-all shadow-neon hover:shadow-primary/50 hover:-translate-y-1 relative overflow-hidden group">
            <span className="relative z-10">Try the Demo</span>
            <div className="absolute inset-0 bg-gradient-to-r from-indigo-500 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </a>
          <a href="/responsible-ai" className="px-8 py-4 rounded-xl bg-white text-slate-700 font-bold text-lg hover:bg-slate-50 border border-slate-200 transition-all hover:border-slate-300 hover:shadow-lg">
            Explainability & Fair AI
          </a>
        </div>
      </section>

      <section className="grid gap-8 md:grid-cols-3 perspective-1000">
        <FeatureCard
          title="Alternative Data"
          desc="Go beyond traditional bureaus. Analyze utility payments, digital wallet volume, and e-commerce trends."
          icon="📊"
          delay={0}
        />
        <FeatureCard
          title="Transparent AI"
          desc="No black boxes. Get SHAP-based explanations for every single score generated by the model."
          icon="🔍"
          delay={100}
        />
        <FeatureCard
          title="Fair & Bias-Free"
          desc="Built-in fairness monitoring ensures equitable outcomes across demographics and income levels."
          icon="⚖️"
          delay={200}
        />
      </section>
    </div>
  );
}

function FeatureCard({ title, desc, icon, delay }: { title: string; desc: string; icon: string; delay: number }) {
  return (
    <div
      className="rounded-2xl bg-white/60 backdrop-blur-sm p-8 shadow-glass border border-white/50 card-hover flex flex-col items-start gap-4 animate-in fade-in slide-in-from-bottom-8 duration-700 fill-mode-backwards"
      style={{ animationDelay: `${delay}ms` }}
    >
      <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-2xl mb-2 group-hover:scale-110 transition-transform duration-300">
        {icon}
      </div>
      <h3 className="text-xl font-bold text-slate-900 group-hover:text-primary transition-colors">{title}</h3>
      <p className="text-slate-600 leading-relaxed">
        {desc}
      </p>
    </div>
  )
}
